# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: rainbowAggregationLogin
spec:
  enabled: true
  requires: ">=2.20.0"
  author:
    name: AMEN
    website: https://www.ymypay.cn
  logo: logo.png
  settingName: rainbowAggregationLogin-settings
  configMapName: rainbowAggregationLogin-configmap
  homepage: https://github.com/2331892928/halo-plugin-rainbowAggregationLoginPlugin#readme
  repo: https://github.com/2331892928/halo-plugin-rainbowAggregationLoginPlugin
  issues: https://github.com/2331892928/halo-plugin-rainbowAggregationLoginPlugin/issues
  displayName: "彩虹聚合登录OAuth2"
  description: "这是彩虹聚合登录插件，聚合了QQ、WX、AliPay等主流和非主流登录，什么是彩虹聚合登录？是由彩虹作者开发的聚合登录系统"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-starter/blob/main/LICENSE"
